services:

  # ----------------------------------------------------------
  # Веб-приложение.
  #
  # Оно отвечает за:
  #   - выдачу временного credential;
  #   - HMAC-подпись;
  #   - QR-код;
  #   - веб-страницу.
  # ----------------------------------------------------------

  dumbproxy-web:
    image: comradekit66/dumbproxy-web:latest

    container_name: dumbproxy-web

    restart: unless-stopped

    # Все настройки приложения находятся
    # во внешнем .env.
    env_file:
      - .env

    # Веб-интерфейс.
    #
    # Снаружи:
    #   http://SERVER:3000
    #
    # Внутри контейнера приложение слушает :3000.
    ports:
      - "3000:3000"

    # HTML не запекаем в Docker image.
    #
    # Это позволяет менять дизайн страницы
    # без пересборки контейнера.
    #
    # :ro = read-only.
    volumes:
      - ./site:/app/site:ro

    # Подключаем web-контейнер к той же сети,
    # где уже работает dumbproxy.
    networks:
      - tempkey

    security_opt:
      - no-new-privileges:true


# ------------------------------------------------------------
# Используем уже существующую сеть dumbproxy.
#
# ВАЖНО:
# сеть должна быть создана compose-файлом dumbproxy.
# ------------------------------------------------------------

networks:

  tempkey:
    external: true
