services:
  dumbproxy-web:
    image: comradekit66/dumbproxy-web:1.0.0
    container_name: dumbproxy-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./site:/app/site:ro
    networks:
      - templink-network
    security_opt:
      - no-new-privileges:true
networks:
  templink-network:
    external: true
