services:
  dumbproxy-web:
    image: comradekit66/dumbproxy-web:1.0.0
    container_name: dumbproxy-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./site:/app/site:ro

  templink-dumbproxy:
    image: ghcr.io/senseunit/dumbproxy:1.51.1-alpine
    container_name: templink-dumbproxy-socks
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /dumbproxy
    command:
      - -bind-address=:1080
      - -mode=socks5
      - -auth=hmac://
    ports:
      - "1080:1080"
